Rover stories V3
Hydroxa/mars-rover-js pull request #14
Opened 2021-10-25 09:45 UTC by jabrilmahamud

2021-10-25 09:49 UTC, jabrilmahamud reviewed
LGTM, I deleted config.js.

2021-10-26 10:14 UTC, Kenneth-Siu requested changes
There are some mysterious files being added/changed that shouldn't be, but the actual main part of the ticket looks really good!

2021-10-26 10:14 UTC, Kenneth-Siu commented on src/backend/apiRoutes.js
> +router.use("/photos",PhotosController)
Why's this changed in a ticket about adding rover descriptions to the homepage frontend?

I see it's not intended to change anything - can you just put everything back to how it was? You can use this file to see what you've changed to make sure everything goes back the way it was.

2021-10-26 10:14 UTC, Kenneth-Siu commented on src/backend/controllers/PhotosController.js
> +import express from "express";
Again, is this file supposed to be here?

2021-10-28 11:17 UTC, closed without merging